server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CafeManager
    username: postgres
    password: 2898111
    driver-class-name: org.postgresql.Driver

  web:
    resources:
      static-locations: classpath:/static/

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      hibernate.enable_lazy_load_no_trans: true
cloudinary:
  cloud_name: dvgxdoljn
  api_key: 483538944958214
  api_secret: tGV9XVTFHU_n7iRjLEdTUVzyiPo

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.web.servlet: DEBUG
    com.yourpackage: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: C:\Users\serez\OneDrive\Документы\учеба\Проект Кафе аналитик\CafeManagerCore\logs\app.log
